# playback
vo=gpu-next
profile=gpu-hq
hwdec=auto

# general and UI
keep-open=always # stop automatically playing next file
cursor-autohide=100
osc=no # using thumbfast osc instead
osd-on-seek=msg-bar

# screenshots
screenshot-sw=no
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-template=mpv-shot-{%F}{%P}-%02n

# subtitles
demuxer-mkv-subtitle-preroll=yes

# sub/audio track language priority
slang=enm,en,eng # enm is english with japanese honorifics
alang=ja,jpn,en,eng